"""Added extra tables

Revision ID: 2b3aafc3c5b9
Revises: 6106dc3ec6f3
Create Date: 2022-01-28 14:11:47.398170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3aafc3c5b9'
down_revision = '6106dc3ec6f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('star',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mailbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('letter', sa.Column('to', sa.String(), nullable=True))
    op.add_column('letter', sa.Column('star', sa.Integer(), nullable=True))
    op.add_column('letter', sa.Column('ts', sa.DateTime(), nullable=True))
    op.add_column('letter', sa.Column('mailbox', sa.Integer(), nullable=True))
    op.add_column('letter', sa.Column('is_important', sa.Boolean(), nullable=True))
    op.add_column('letter', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.alter_column('letter', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('letter', 'user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'letter', 'star', ['star'], ['id'])
    op.create_foreign_key(None, 'letter', 'mailbox', ['mailbox'], ['id'])
    op.drop_column('letter', 'receiver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letter', sa.Column('receiver', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'letter', type_='foreignkey')
    op.drop_constraint(None, 'letter', type_='foreignkey')
    op.alter_column('letter', 'user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('letter', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('letter', 'is_read')
    op.drop_column('letter', 'is_important')
    op.drop_column('letter', 'mailbox')
    op.drop_column('letter', 'ts')
    op.drop_column('letter', 'star')
    op.drop_column('letter', 'to')
    op.drop_table('mailbox')
    op.drop_table('star')
    # ### end Alembic commands ###
