"""Added Letter table, corrected fk

Revision ID: 6106dc3ec6f3
Revises: 4da5bd798fd5
Create Date: 2022-01-24 10:18:45.710013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6106dc3ec6f3'
down_revision = '4da5bd798fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letter', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'letter', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'letter', type_='foreignkey')
    op.drop_column('letter', 'user')
    # ### end Alembic commands ###
