"""correct  constraint

Revision ID: 8be7890e37ec
Revises: ed10f94a5308
Create Date: 2022-01-28 14:15:33.676317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be7890e37ec'
down_revision = 'ed10f94a5308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letter', sa.Column('size', sa.Integer(), nullable=False))
    op.alter_column('letter', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('letter', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('letter', 'size')
    # ### end Alembic commands ###
