"""Added constraint

Revision ID: ed10f94a5308
Revises: 2b3aafc3c5b9
Create Date: 2022-01-28 14:12:49.096139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed10f94a5308'
down_revision = '2b3aafc3c5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('letter', 'to',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('letter', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('letter', 'ts',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('letter', 'mailbox',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('letter', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('letter', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('letter', 'mailbox',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('letter', 'ts',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('letter', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('letter', 'to',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
